---
name: Python package build and publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.12"
          pypi_token: ${{ secrets.DEPLOY_FROM_GITHUB_KAARTMAKER}}

      - name: Create a Release on GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
